# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clovapi < Formula
  desc "CLI profile switcher for coding agents"
  homepage "https://github.com/joohw/clovapi"
  version "0.1.25"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/joohw/clovapi/releases/download/v0.1.25/clovapi_0.1.25_darwin_amd64.tar.gz"
      sha256 "d3d7ba754b6ee97ee36657f3fb1ca19290fb19e6a3abdc05d596d8a905ced8e7"

      define_method(:install) do
        bin.install "clovapi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/joohw/clovapi/releases/download/v0.1.25/clovapi_0.1.25_darwin_arm64.tar.gz"
      sha256 "e73eee27b4979bf324e54d1e33c8c578db7511f0ab6c7ecd81b99fe75c27d3c7"

      define_method(:install) do
        bin.install "clovapi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/joohw/clovapi/releases/download/v0.1.25/clovapi_0.1.25_linux_amd64.tar.gz"
      sha256 "69626c63be6ab7924e3af176d2ecff00ad3986e17e5d2ef46418d5bfe5e5f28e"
      define_method(:install) do
        bin.install "clovapi"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/joohw/clovapi/releases/download/v0.1.25/clovapi_0.1.25_linux_arm64.tar.gz"
      sha256 "2b731e2ea0628ef05dd8c6cb270f67a4d96b8345474e7318cc29804cc4f881b6"
      define_method(:install) do
        bin.install "clovapi"
      end
    end
  end

  test do
    system "#{bin}/clovapi", "--help"
  end
end
