# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clovapi < Formula
  desc "CLI profile switcher for coding agents"
  homepage "https://github.com/joohw/clovapi"
  version "0.1.12"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/joohw/clovapi/releases/download/v0.1.12/clovapi_0.1.12_darwin_amd64.tar.gz"
      sha256 "11446aa85bce464133ae317a94bea70cb245e3a4dc9caeebca4fc8d4aa48cff7"

      define_method(:install) do
        bin.install "clovapi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/joohw/clovapi/releases/download/v0.1.12/clovapi_0.1.12_darwin_arm64.tar.gz"
      sha256 "643c04dbccf15ad371f9369953538e6c5096c09dc31c4f647cd5d5b7fad44254"

      define_method(:install) do
        bin.install "clovapi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/joohw/clovapi/releases/download/v0.1.12/clovapi_0.1.12_linux_amd64.tar.gz"
      sha256 "fe2a422aa257a3ae1b70d458e38beca08a60b8ad702fa65ab75ecdd2809c5171"
      define_method(:install) do
        bin.install "clovapi"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/joohw/clovapi/releases/download/v0.1.12/clovapi_0.1.12_linux_arm64.tar.gz"
      sha256 "7cd342d954070ed720a247c9ceb55d4fc74d9a08f6cfc36fa57ed7b05191753f"
      define_method(:install) do
        bin.install "clovapi"
      end
    end
  end

  test do
    system "#{bin}/clovapi", "--help"
  end
end
