# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clovapi < Formula
  desc "CLI profile switcher for coding agents"
  homepage "https://github.com/joohw/clovapi"
  version "0.1.27"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/joohw/clovapi/releases/download/v0.1.27/clovapi_0.1.27_darwin_amd64.tar.gz"
      sha256 "26b9da883f5224b8059e9ce4fa16cb575cfe2da344a6722cc9f157d9b5ed769c"

      define_method(:install) do
        bin.install "clovapi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/joohw/clovapi/releases/download/v0.1.27/clovapi_0.1.27_darwin_arm64.tar.gz"
      sha256 "01714c7a08467abab3ec1dcde94f92f5eb3c3a0002ab81dd0dd37006caa79e94"

      define_method(:install) do
        bin.install "clovapi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/joohw/clovapi/releases/download/v0.1.27/clovapi_0.1.27_linux_amd64.tar.gz"
      sha256 "fb04bace6108feaeb658e800caf95825969d925093fb4d57c8f4a003249e860a"
      define_method(:install) do
        bin.install "clovapi"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/joohw/clovapi/releases/download/v0.1.27/clovapi_0.1.27_linux_arm64.tar.gz"
      sha256 "32d4f19aea4c1182896f480cc8e8a7f274effa0abe0f1eb944ad8b5133b32fff"
      define_method(:install) do
        bin.install "clovapi"
      end
    end
  end

  test do
    system "#{bin}/clovapi", "--help"
  end
end
